packages:
  - .

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
  - workerd

overrides:
  path-to-regexp@>=4.0.0 <6.3.0: ">=6.3.0"
  esbuild@<=0.24.2: ">=0.25.0"
